apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notification-manager-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: notification-manager-controller-role
subjects:
- kind: ServiceAccount
  name: notification-manager-sa
  namespace: {{ .Release.Namespace }}
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notification-manager-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: notification-manager-proxy-role
subjects:
- kind: ServiceAccount
  name: notification-manager-sa
  namespace: {{ .Release.Namespace }}

{{- if .Values.kubesphere.enabled }}
{{- if or (eq .Values.kubesphere.version "v3.1.0")  (eq .Values.kubesphere.version "v3.2.0") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notification-manager-tenant-sidecar-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: notification-manager-tenant-sidecar-role
subjects:
  - kind: ServiceAccount
    name: notification-manager-sa
    namespace: {{ .Release.Namespace }}
{{- end}}
{{- end}}
