apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
resources:
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- service_account.yaml
- auth_proxy_service.yaml
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_client_clusterrole.yaml

  # This is for tenant sidecar in kubesphere, if the notification manager not run in the kubesphere,comment out it.
patches:
- path: patches/patch.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: controller-role
    version: v1
